# Generated by Django 3.1.7 on 2023-03-30 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockQuant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('location_id', models.IntegerField()),
                ('quantity', models.FloatField()),
                ('reserved_quantity', models.FloatField()),
                ('available_quantity', models.FloatField()),
                ('create_date', models.DateTimeField()),
                ('write_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'stock_quant',
                'managed': False,
            },
        ),
    ]
