# Generated by Django 3.1.7 on 2023-03-31 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockquant',
            options={},
        ),
    ]
